---
title: "Confounding effect on joined coal trees"
author: "Xavier Didelot"
date: '`r Sys.Date()`'
output:
  pdf_document: default
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Confounding effect on joined coal trees}
  %\usepackage[utf8]{inputenc}
---

First we generate a dated tree with root in 2000 and five populations existing for only a year each and separated by 5 years.

```{r}
library(BactDating)
library(ape)
set.seed(0)
t1=rcoal(30)
h1=dist.nodes(t1)[1,Ntip(t1)+1]
t1$root.edge=10-h1
t2=rcoal(30)
h2=dist.nodes(t2)[1,Ntip(t2)+1]
t2$root.edge=10.1-h2
t3=rcoal(30)
h3=dist.nodes(t3)[1,Ntip(t3)+1]
t3$root.edge=10.2-h3
dt=bind.tree(t1,t2,position=t1$root.edge)
dt=bind.tree(dt,t3,position=dt$root.edge)
dates=unname(dist.nodes(dt)[Ntip(dt)+1,1:Ntip(dt)])
dt$root.time=2000
dates=dates+dt$root.time
plot(dt,show.tip.label=F)
axisPhylo(1,backward = F)
```

Next we generate a phylogenetic tree using a Poisson(10) mutation model:
```{r}
tree=simobsphy(dt,mu=10,model='poisson')
plot(tree,show.tip.label = F)
axisPhylo(1,backward=F)
```


Root-to-tip analysis:
```{r}
res=roottotip(tree,dates)
```

BactDating analysis:

```{r}
r=bactdate(tree,dates,model='poisson',updateRoot = F)
plot(r,'trace')
plot(r,'treeCI',show.tip.label=F)
print(r)
```
