---
title: "Confounding effect on Master simulation"
author: "Xavier Didelot"
date: '`r Sys.Date()`'
output:
  pdf_document: default
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Confounding effect on Master simulation}
  %\usepackage[utf8]{inputenc}
---

First we generate a dated tree with three populations existing for only 1 year each and separated by 1 years.

```{r}
library(BactDating)
library(ape)
library(confounding)
set.seed(0)
s=list(runif(30,2010,2010.1),runif(30,2010.1,2010.2),runif(30,2010.2,2010.3))
dt=simMaster(samplingDates=s,demes=3,coalrate = 5,migrate = 0.1)
dates=unname(dist.nodes(dt)[Ntip(dt)+1,1:Ntip(dt)])+dt$root.time
plot(dt,show.tip.label=F)
axisPhylo(1,backward = F)
```

Next we generate a phylogenetic tree using a Poisson(10) mutation model:
```{r}
tree=simobsphy(dt,mu=10,model='poisson')
plot(tree,show.tip.label = F)
axisPhylo(1,backward=F)
```

Root-to-tip regression:
```{r}
r=roottotip(tree,dates)
```

Run all analysis methods:
```{r}
for (a in 1:4) {
  r=runDating(tree,dates,algo=a)
  plot(r,show.tip.label=F)
  print(r)
}
```
