---
title: "Confounding effect on structured simulation"
author: "Xavier Didelot"
date: '`r Sys.Date()`'
output:
  pdf_document: default
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Confounding effect on structured simulation}
  %\usepackage[utf8]{inputenc}
---

First we generate a dated tree with three populations. Each population is sampled 30 times in non-overlapping windows of 0.1 year each.

```{r}
library(BactDating)
library(ape)
library(confounding)
set.seed(1)
s=list(runif(30,2010,2010.1),runif(30,2010.1,2010.2),runif(30,2010.2,2010.3))
dt=simStructure(popStarts=c(2009,2009,2009),samplingDates=s)
dates=unname(dist.nodes(dt)[Ntip(dt)+1,1:Ntip(dt)])+dt$root.time
plot(dt,show.tip.label=F)
axisPhylo(1,backward = F)
```

Next we generate a phylogenetic tree using a Poisson(10) mutation model:
```{r}
tree=simobsphy(dt,mu=10,model='poisson')
plot(tree,show.tip.label = F)
axisPhylo(1,backward=F)
```


Root-to-tip analysis:
```{r}
res=roottotip(tree,dates)
```

BactDating analysis:

```{r}
r=bactdate(tree,dates,model='poisson',updateRoot = F)
plot(r,'trace')
plot(r,'treeCI',show.tip.label=F)
print(r)
```
