---
title: "Pseudo-residual analysis"
author: "Xavier Didelot"
date: '`r Sys.Date()`'
output:
  html_document: default
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Pseudo-residual analysis}
  %\usepackage[utf8]{inputenc}
---

We start by generating a dated tree with no structure and a small effective population size 
$N_e g=1$ year relative to the sampling frame of 10 years between 2010 and 2020:

```{r}
library(BactDating)
library(ape)
library(ValidateDating)
set.seed(0)
dates=runif(100,2010,2020)
dt=simcoaltree(dates,alpha=1)
plot(dt,show.tip.label = F)
axisPhylo(backward = F)
```

Next we generate a phylogenetic tree using a Poisson(10) mutation model:
```{r}
tree=simobsphy(dt,mu=10,model='poisson')
plot(tree,show.tip.label = F)
axisPhylo(1,backward=F)
```

A root-to-tip regression analysis works perfectly:

```{r}
res=roottotip(tree,dates)
```

Run all dating methods with pseudo-residual analysis:
```{r}
for (a in 1:5) {
  r=runDating(tree,dates,algo=a)
  print(r)
  plot(r,show.tip.label=F)
  plotProbBranches(r)
  plotResid(r)
  print(testResid(r))
}
```
