---
title: "Confounding effect on DetectImport simulation"
author: "Xavier Didelot"
date: '`r Sys.Date()`'
output:
  html_document: default
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Confounding effect on DetectImport simulation}
  %\usepackage[utf8]{inputenc}
---

First we generate a dated tree with three populations existing for only 1 year each and separated by 1 years.

```{r}
library(DiagnoDating,quietly=T)
library(DetectImports)
set.seed(0)
NeFunImp=function(t,texp) {return(pmax(0,(t-texp)-(t-texp)^2))}
xs=seq(0,2,0.01);plot(xs,NeFunImp(xs,0),type='l',xlab='Time since pop start',ylab='Pop size')
dt=simImports(localPopStart = 2000,importDates=c(2001,2002),samplingStartDate = 2000,samplingEndDate = 2100,samplingNumber = 100,globalNeg = 10,NeFunImp = NeFunImp)
dates=dt$stats[,'dates'][1:Ntip(dt)]
plot(dt,show.tip.label=F)
axisPhylo(1,backward = F)
```

Next we generate a phylogenetic tree using a Poisson(10) mutation model:
```{r}
tree=simobsphy(dt,mu=10,model='poisson')
roottotip(tree,dates)
```

Run and diagnose BactDating:
```{r}
r=runDating(tree,dates,algo=3,nbIts=2e4)
rb=r;class(rb)<-'resBactDating'
plot(rb,'treeCI',show.tip.label=F)
print(rb)
plot(rb,'trace')
postdistpvals(r,showPlot = T)
```
