library(DiagnoDating,quietly=T)
library(phangorn)
rm(list=ls())
source('fig_label.R')
set.seed(1)
dates=runif(100,2010,2020)
dt=simcoaltree(dates,alpha=1)

tree=simobsphy(dt,mu=10,sigma=5,model='arc')

pdf('exampleS1.pdf',12,8)
roottotip(initRoot(tree,dates),dates)
dev.off()
system('open exampleS1.pdf')

tree=unroot(midpoint(tree))
suppressWarnings(r0<-resDating(dt,tree,rate=10,model = 'poisson')) #fine to ignore warning
r=runDating(tree,dates,algo='BactDating',model='poisson',showProgress=T)
r2=runDating(tree,dates,algo='BactDating',model='arc',showProgress=T)
modelcompare(r,r2)

modr=r;class(modr)<-'resBactDating';print(modr)
modr2=r2;class(modr2)<-'resBactDating';print(modr2)
sr=takeSample(r)
sr2=takeSample(r2)

pdf('exampleResid.pdf',6,6)
par(mfrow=c(2,2),mar=c(4,4,2,2))
#plot(dt,show.tip.label = F)
#fig_label('A',cex=2)
#axisPhylo(1,backward = F)
#plotLikBranches(r0,sub=1,minProb=1e-3)
#fig_label('B',cex=2)
plotResid(sr,3,main='',xlim=c(-4,4),xlab='Residuals',ylim=c(0,0.5),breaks=seq(-10,10,0.5))
fig_label('A',cex=2)
plotResid(sr,4,main='',xlim=c(-3,3),ylim=c(-4,4))
fig_label('B',cex=2)
plotResid(sr2,3,main='',xlim=c(-4,4),xlab='Residuals',ylim=c(0,0.5),breaks=seq(-10,10,0.5))
fig_label('C',cex=2)
plotResid(sr2,4,main='',xlim=c(-3,3),ylim=c(-4,4))
fig_label('D',cex=2)
dev.off()
system('open exampleResid.pdf')

testResid(sr)
testResid(sr2)

set.seed(0)
pdf('exampleS2.pdf',6,10)
par(mfrow=c(2,1))
v =postdistpvals(r ,showPlot=T)
fig_label('A',cex=2)
v2=postdistpvals(r2,showPlot=T)
fig_label('B',cex=2)
dev.off()
system('open exampleS2.pdf')

if (F) {
set.seed(0)
a1=runDating(tree,dates,algo='LSD')
a2=runDating(tree,dates,algo='node.dating')
a3=runDating(tree,dates,algo='treedater')
a4=runDating(tree,dates,algo='TreeTime')

pdf('exampleS3.pdf',10,10)
par(mfrow=c(2,2),mar=c(4,4,2,2))
plotResid(a1,3,main='',xlim=c(-4,4),xlab='Residuals',ylim=c(0,0.5),breaks=seq(-10,10,0.5))
fig_label('A',cex=2)
plotResid(a2,3,main='',xlim=c(-4,4),xlab='Residuals',ylim=c(0,0.5),breaks=seq(-10,10,0.5))
fig_label('B',cex=2)
plotResid(a3,3,main='',xlim=c(-4,4),xlab='Residuals',ylim=c(0,0.5),breaks=seq(-10,10,0.5))
fig_label('C',cex=2)
plotResid(a4,3,main='',xlim=c(-4,4),xlab='Residuals',ylim=c(0,0.5),breaks=seq(-10,10,0.5))
fig_label('D',cex=2)
dev.off()
system('open exampleS3.pdf')
}

set.seed(1)
pdf('examplePPCheck1.pdf',10,10)
ppcheck(r,showPlot = T)
dev.off()
system('open examplePPCheck1.pdf')

pdf('examplePPCheck2.pdf',10,10)
ppcheck(r2,showPlot = T)
dev.off()
system('open examplePPCheck2.pdf')
